


run:
	clear
		#c++ -o main.exe $(wildcard *.cpp) -larmadillo
		#c++ *.cpp -o a
		#./main.exe
	g++ -o main.exe main.cpp planet.cpp solarsystem.cpp -larmadillo
	./main.exe
	python plott.py
	#python plott_energy.py

run_perihelion:
	clear
		#c++ -o main.exe $(wildcard *.cpp) -larmadillo
		#c++ *.cpp -o a
		#./main.exe
	g++ -o perihelion_main.exe perihelion_main.cpp perihelion_planet.cpp perihelion_solarsystem.cpp -larmadillo
	./perihelion_main.exe
	python plott.py
